server:
  port: 8000

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_ADDRESS}
      database: demo
      authentication: admin

  redis:
    url: redis://${REDIS_USERNAME}:${REDIS_PASSWORD}@${REDIS_ADDRESS}
    timeout: 1000

cloud:
  env: ${CLOUD_ENV}

